<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <title>后台管理</title>
    <link rel="stylesheet" type="text/css" href="{STATIC_PATH}/css/common.css"/>
    <link rel="stylesheet" type="text/css" href="{STATIC_PATH}/css/main.css"/>
    <script type="text/javascript" src="{STATIC_PATH}/js/libs/modernizr.min.js"></script>
</head>
<body>
<div class="topbar-wrap white">
    <div class="topbar-inner clearfix">
        <div class="topbar-logo-wrap clearfix">
            <h1 class="topbar-logo none"><a href="{PUBLIC_PATH}news/index " class="navbar-brand">后台管理</a></h1>
            <ul class="navbar-list clearfix">
                <li><a class="on" href="{PUBLIC_PATH}news/index ">首页</a></li>
                <li><a href="#" target="_blank">网站首页</a></li>
            </ul>
        </div>
        <div class="top-info-wrap">
            <ul class="top-info-list clearfix">
                <li><a href="http://www.jscss.me">管理员</a></li>
                <li><a href="http://www.jscss.me">修改密码</a></li>
                <li><a href="http://www.jscss.me">退出</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="container clearfix">
    <div class="sidebar-wrap">
        <div class="sidebar-title">
            <h1></h1>
        </div>
        <div class="sidebar-content">
            <ul class="sidebar-list">
                <li>
                    <a href="#"><i class="icon-font">&#xe003;</i>分类管理</a>
                    <ul class="sub-menu">
                        <li><a href="{PUBLIC_PATH}type/index"><i class="icon-font">&#xe008;</i>管理分类</a></li>
                        <li><a href="{PUBLIC_PATH}type/add"><i class="icon-font">&#xe005;</i>添加分类</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#"><i class="icon-font">&#xe018;</i>新闻管理</a>
                    <ul class="sub-menu">
                        <li><a href="{PUBLIC_PATH}news/index"><i class="icon-font">&#xe017;</i>管理新闻</a></li>
                        <li><a href="{PUBLIC_PATH}news/add"><i class="icon-font">&#xe037;</i>添加新闻</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#"><i class="icon-font">&#xe018;</i>管理员管理</a>
                    <ul class="sub-menu">
                        <li><a href="{PUBLIC_PATH}users/index"><i class="icon-font">&#xe017;</i>管理管理员</a></li>
                        <li><a href="{PUBLIC_PATH}users/add"><i class="icon-font">&#xe037;</i>添加管理员</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#"><i class="icon-font">&#xe018;</i>角色管理</a>
                    <ul class="sub-menu">
                        <li><a href="{PUBLIC_PATH}roles/index"><i class="icon-font">&#xe017;</i>管理角色</a></li>
                        <li><a href="{PUBLIC_PATH}roles/add"><i class="icon-font">&#xe037;</i>添加角色</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#"><i class="icon-font">&#xe018;</i>评论管理</a>
                    <ul class="sub-menu">
                        <li><a href="{PUBLIC_PATH}comments/index"><i class="icon-font">&#xe017;</i>管理评论</a></li>
                        <li><a href="{PUBLIC_PATH}comments/add"><i class="icon-font">&#xe037;</i>添加评论</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
<!--/sidebar-->
    <div class="main-wrap">

        <div class="crumb-wrap">
            <div class="crumb-list"><i class="icon-font"></i><a href="/">首页</a><span class="crumb-step">&gt;</span><a class="crumb-name" href="{PUBLIC_PATH}news/index">新闻管理</a><span class="crumb-step">&gt;</span><span>编辑新闻</span></div>
        </div>
        <div class="result-wrap">
            <form action="{PUBLIC_PATH}news/add" method="post" id="myform" name="myform" enctype="multipart/form-data">
               <table class="insert-tab" width="100%">
                    <tbody>
                        <tr>
                            <th width="120"><i class="require-red">*</i>类别：</th>
                            <td>
                                <select name="type">
                                    {foreach $types as $type}
                                        <option value="{$type.id}" {if $type.id==$news.typeid}selected{/if}>{$type.name}</option>
                                    {/foreach}
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <th><i class="require-red">*</i>标题：</th>
                            <td>
                                <input type="text" name="title"  class="common-text" size="80" value="{$news.title}" />
                            </td>
                        </tr>
                        <tr>
                            <th><i class="require-red">*</i>摘要：</th>
                            <td>
                                <textarea class="common-textarea" name="description" cols="30" style="width: 98%;" rows="5">{$news.description}</textarea>
                            </td>
                        </tr>
                        <tr>
                            <th><i class="require-red">*</i>内容：</th>
                            <td>
                                <textarea class="common-textarea" name="content" cols="30" style="width: 98%;" rows="15">{$news.content}</textarea>
                            </td>
                        </tr>
                        <tr>
                            <th></th>
                            <td>
                                <input class="btn btn-primary btn6 mr10" value="修改" type="submit" name="submit">
                                 <input class="btn btn6" onclick="history.go(-1)" value="返回" type="button">
                            </td>
                        </tr>
                        </tbody></table>
            </form>
        </div>
    </div>
    <!--/main-->
</div>
</body>
</html>