<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <title>后台管理</title>
    <link rel="stylesheet" type="text/css" href="{STATIC_PATH}/css/common.css"/>
    <link rel="stylesheet" type="text/css" href="{STATIC_PATH}/css/main.css"/>
    <script type="text/javascript" src="{STATIC_PATH}/js/libs/modernizr.min.js"></script>
</head>
<body>
<div class="topbar-wrap white">
    <div class="topbar-inner clearfix">
        <div class="topbar-logo-wrap clearfix">
            <h1 class="topbar-logo none"><a href="{PUBLIC_PATH}news/index " class="navbar-brand">后台管理</a></h1>
            <ul class="navbar-list clearfix">
                <li><a class="on" href="{PUBLIC_PATH}news/index ">首页</a></li>
                <li><a href="#" target="_blank">网站首页</a></li>
            </ul>
        </div>
        <div class="top-info-wrap">
            <ul class="top-info-list clearfix">
                <li><a href="http://www.jscss.me">管理员</a></li>
                <li><a href="http://www.jscss.me">修改密码</a></li>
                <li><a href="http://www.jscss.me">退出</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="container clearfix">
    <div class="sidebar-wrap">
    	<div class="sidebar-title">
            <h1></h1>
        </div>
        <div class="sidebar-content">
            <ul class="sidebar-list">
                <li>
                    <a href="#"><i class="icon-font">&#xe003;</i>分类管理</a>
                    <ul class="sub-menu">
                        <li><a href="{PUBLIC_PATH}type/index"><i class="icon-font">&#xe008;</i>管理分类</a></li>
                        <li><a href="{PUBLIC_PATH}type/add"><i class="icon-font">&#xe005;</i>添加分类</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#"><i class="icon-font">&#xe018;</i>新闻管理</a>
                    <ul class="sub-menu">
                        <li><a href="{PUBLIC_PATH}news/index"><i class="icon-font">&#xe017;</i>管理新闻</a></li>
                        <li><a href="{PUBLIC_PATH}news/add"><i class="icon-font">&#xe037;</i>添加新闻</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#"><i class="icon-font">&#xe018;</i>管理员管理</a>
                    <ul class="sub-menu">
                        <li><a href="{PUBLIC_PATH}users/index"><i class="icon-font">&#xe017;</i>管理管理员</a></li>
                        <li><a href="{PUBLIC_PATH}users/add"><i class="icon-font">&#xe037;</i>添加管理员</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#"><i class="icon-font">&#xe018;</i>角色管理</a>
                    <ul class="sub-menu">
                        <li><a href="{PUBLIC_PATH}roles/index"><i class="icon-font">&#xe017;</i>管理角色</a></li>
                        <li><a href="{PUBLIC_PATH}roles/add"><i class="icon-font">&#xe037;</i>添加角色</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#"><i class="icon-font">&#xe018;</i>评论管理</a>
                    <ul class="sub-menu">
                        <li><a href="{PUBLIC_PATH}comments/index"><i class="icon-font">&#xe017;</i>管理评论</a></li>
                        <li><a href="{PUBLIC_PATH}comments/add"><i class="icon-font">&#xe037;</i>添加评论</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
    <!--/sidebar-->
    <div class="main-wrap">

        <div class="crumb-wrap">
            <div class="crumb-list"><i class="icon-font"></i><a href="/">首页</a><span class="crumb-step">&gt;</span><span class="crumb-name">新闻管理</span></div>
        </div>
        <div class="result-wrap">
            <form name="myform" id="myform" method="post">
                <div class="result-title">
                    <div class="result-list">
                        <a href="{PUBLIC_PATH}news/add"><i class="icon-font"></i>添加新闻</a>
                    </div>
                </div>
                <div class="result-content">
                    <table class="result-tab" width="100%">
                        <tr>
                            <th class="tc" width="5%"><input class="allChoose" name="" type="checkbox"></th>
                            <th>ID</th>
                            <th>标题</th>
                            <th>作者</th>
                            <th>发布时间</th>
                            <th>更新时间</th>
                            <th>操作</th>
                        </tr>
                        {foreach $news as $tmp}
                             <tr>
                                <td class="tc"><input name="id[]" value="59" type="checkbox"></td>
                                <td>{$tmp.id}</td>
                                <td><a class="link-del" href="{PUBLIC_PATH}news/view/id/{$tmp.id}">{$tmp.title}</a></td>
                                <td title="">李小雨
                                </td>
                                <td>{$tmp.inputtime|date_format:"Y-m-d H:i:s"}</td>
                                <td>{$tmp.updatetime|date_format:"Y-m-d H:i:s"}</td>
                                <td>
                                    <a class="link-update" href="{PUBLIC_PATH}news/edit/id/{$tmp.id}">修改</a>
                                    <a class="link-del" href="{PUBLIC_PATH}news/delete/id/{$tmp.id}">删除</a>
                                     <a class="link-del" href="{PUBLIC_PATH}news/view/id/{$tmp.id}">详情</a>
                                </td>
                            </tr>
                        {/foreach}
                    </table>
                    <div class="list-page"> 2 条 1/1 页</div>
                </div>
            </form>
        </div>
    </div>
    <!--/main-->
</div>
</body>
</html>