<!DOCTYPE html>
<html>
<head>
	<title>{$news.title}</title>
	<style>
		*{
			font-size: 16px;
			line-height: 1.5em;
		}
		h1{
			text-align:center;
		}
		p.subhead{
			text-align: center;
			font-size:12px;
			color:#666;
			text-indent: 0;
		}
		p{
			text-indent: 2em;
		}
	</style>
</head>
<body>
<div class="breadcrumb">首页 > <a href="{PUBLIC_PATH}news/index">新闻管理 </a>查看新闻</div>
	<h1>{$news.title}</h1>
	<p class="subhead">发布时间：{$news.inputtime|date_format:"Y-m-d H:i:s"}</p>
	<p>摘要：{$news.description}</p>
	<p>{$news.content}</p>
</body>
</html>