<!DOCTYPE html>
<html>
<head>
	<title>{$users.username}</title>
	<style>
		*{
			font-size: 16px;
			line-height: 1.5em;
		}
		h1{
			text-align:center;
		}
		p.subhead{
			text-align: center;
			font-size:12px;
			color:#666;
			text-indent: 0;
		}
		p{
			text-indent: 2em;
		}
	</style>
</head>
<body>
<div class="breadcrumb">首页 > <a href="{PUBLIC_PATH}users/index">管理员管理 </a>查看管理员</div>
	<h1>管理员名称：{$users.username}</h1>
	<h1>邮箱：{$users.email}</h1>
	<h1>问题：{$users.question}</h1>
	<h1>答案：{$users.answer}</h1>
	<p class="subhead">注册时间：{$users.registerTime|date_format:"Y-m-d H:i:s"}</p>>
</body>
</html>