<!DOCTYPE html>
<html>
<head>
	<title>{$types.name}</title>
	<style>
		*{
			font-size: 16px;
			line-height: 1.5em;
		}
		h1{
			text-align:center;
		}
		p.subhead{
			text-align: center;
			font-size:12px;
			color:#666;
			text-indent: 0;
		}
		p{
			text-indent: 2em;
		}
	</style>
</head>
<body>
<div class="breadcrumb">首页 > <a href="{PUBLIC_PATH}type/index">分类管理 </a>查看分类</div>
	<h1>类别：{$types.name}</h1>
	<p class="subhead">发布时间：{$types.inputtime|date_format:"Y-m-d H:i:s"}</p>
	<p>描述：{$types.description}</p>
</body>
</html>
 